.phony all:
all: a3disk 

a3disk:
	gcc -Wall a3functions.c diskinfo.c -g -o diskinfo
	gcc -Wall a3functions.c disklist.c -g -o disklist
	gcc -Wall a3functions.c diskget.c -g -o diskget
	gcc -Wall a3functions.c diskput.c -g -o diskput
